CREATE DATABASE IF NOT EXISTS academydb DEFAULT CHARACTER SET utf8mb4;

USE academydb;

CREATE TABLE IF NOT EXISTS students(
	id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    school VARCHAR(100) NOT NULL,
    grade int NOT NULL,
	name VARCHAR(100) NOT NULL,
    date VARCHAR(100) NOT NULL,
    d_date VARCHAR(100) NOT NULL,
    commit VARCHAR(100),
    etc VARCHAR(1000)
);